# Generated by Django 4.0.1 on 2022-01-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(verbose_name='Longer URL')),
                ('short_url', models.CharField(max_length=15, unique=True, verbose_name='Shorter URL')),
                ('request_times', models.IntegerField(default=0, verbose_name='Shorter URL Requested Times')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'URLRecords',
                'verbose_name_plural': 'URLRecords',
                'db_table': 'URLRecords',
            },
        ),
    ]
